services:
  nosqldata:
    image: mongo
    
  postgres:
    image: postgres
    
  cache:
    image: "redis:alpine"

  seq:
    image: datalust/seq:latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  identity.api:
    image: ${DOCKER_REGISTRY-}identity.api
    build:
      context: .
      dockerfile: src/Services/Identity/Career.Identity/Dockerfile
    depends_on:
      - postgres
      - seq
  
  definition.api:
    image: ${DOCKER_REGISTRY-}definition.api
    build:
      context: .
      dockerfile: src/Services/Definition/Definition.Api/Dockerfile
    depends_on:
      - nosqldata
      - cache
      - seq
        
  company.api:
    image: ${DOCKER_REGISTRY-}company.api
    build:
      context: .
      dockerfile: src/Services/Company/Company.Api/Dockerfile
    depends_on:
      - postgres
      - nosqldata
      - rabbitmq
      - seq
        
  job.api:
    image: ${DOCKER_REGISTRY-}job.api
    build:
      context: .
      dockerfile: src/Services/Job/Job.Api/Dockerfile
    depends_on:
      - nosqldata
      - rabbitmq
      - seq
        
  cv.api:
    image: ${DOCKER_REGISTRY-}cv.api
    build:
      context: .
      dockerfile: src/Services/CV/CV.Api/Dockerfile
    depends_on:
      - nosqldata
      - rabbitmq
      - seq