version: '3.4'

services:
  nosqldata:
    container_name: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ${HOST_VOLUMES_PATH}/mongo:/data/db

  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - ${HOST_VOLUMES_PATH}/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    
  cache:
    container_name: "cache"
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    volumes:
      - ${HOST_VOLUMES_PATH}/redis/redis-data:/var/lib/redis
      - ${HOST_VOLUMES_PATH}/redis/redis.conf:/usr/local/etc/redis/redis.conf

  seq:
    container_name: "seq"
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - ${HOST_VOLUMES_PATH}/seq:/data

  definition.api:
    container_name: "definition.api"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV}
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"

  company.api:
    container_name: "company.api"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV}
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5002:80"

  job.api:
    container_name: "job.api"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV}
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5003:80"